repos:
    - repo: https://github.com/psf/black-pre-commit-mirror
      rev: 23.9.1
      hooks:
        - id: black-jupyter
          args: [--line-length=79]
          # It is recommended to specify the latest version of Python
          # supported by your project here, or alternatively use
          # pre-commit's default_language_version, see
          # https://pre-commit.com/#top_level-default_language_version
          language_version: python3.11
    - repo: https://github.com/pycqa/flake8
      rev: 'faef3587480ab621dd2fd2d87ec36fc479749a90'  # pick a git hash / tag to point to
      hooks:
        - id: flake8
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0 
      hooks:
        - id: check-added-large-files