repos:
    - repo: https://github.com/psf/black-pre-commit-mirror
      rev: 23.9.1
      hooks:
        - id: black-jupyter
          # It is recommended to specify the latest version of Python
          # supported by your project here, or alternatively use
          # pre-commit's default_language_version, see
          # https://pre-commit.com/#top_level-default_language_version
          language_version: python3.11
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0 
      hooks:
        - id: check-added-large-files